version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: knowledge_base_db
    environment:
      POSTGRES_DB: notedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "9090:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
